data_paths:
  base_path: "D:/DEMAND_FORECASTING_SYSTEM/data/processed"

  orders: "blinkit_orders_clean.csv"
  order_items: "blinkit_order_items_clean.csv"
  customers: "blinkit_customers_clean.csv"
  products: "blinkit_products_clean.csv"
  inventory: "blinkit_inventory_clean.csv"
  marketing: "blinkit_marketing_clean.csv"
  weather: "blinkit_weather_clean.csv"

output:
  processed_dir: "D:/DEMAND_FORECASTING_SYSTEM/data/processed"
  orders_features: "orders_features.csv"

logging:
  log_dir: "D:/DEMAND_FORECASTING_SYSTEM/data_pipeline/logs"
  log_file: "pipeline.log"
